
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 13 20:26:16 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int deleteOne = 9;
  public static final int Numero = 19;
  public static final int ERROR = 20;
  public static final int Identificador = 18;
  public static final int Comillas = 17;
  public static final int update = 8;
  public static final int PuntoDoble = 15;
  public static final int Coma = 16;
  public static final int ParentesisC = 12;
  public static final int LlaveC = 14;
  public static final int filter = 7;
  public static final int insertOne = 4;
  public static final int ParentesisA = 11;
  public static final int LlaveA = 13;
  public static final int close = 10;
  public static final int collection = 3;
  public static final int EOF = 0;
  public static final int find = 5;
  public static final int updateOne = 6;
  public static final int error = 1;
  public static final int use = 2;
}

